config_version = 14

[bar.default]
background_opacity = 0.87999998033046722
start = [ "launcher", "workspaces", "active_window" ]

[calendar]
enabled = true

    [calendar.account.personal_google]
    type = "google"

[control_center.calendar]
show_events_card = false

[desktop_widgets]
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000008",
    "desktop-widget-0000000000000010",
    "desktop-widget-0000000000000009",
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000003",
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000005"
]

    [desktop_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000010]
    box_height = 240.0
    box_width = 367.0
    cx = 1826.2
    cy = 707.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "label"

        [desktop_widgets.widget.desktop-widget-0000000000000010.settings]
        background = true
        opacity = 1.0
        title = ""

    [desktop_widgets.widget.desktop-widget-0000000000000009]
    box_height = 110.0
    box_width = 335.0
    cx = 1826.2
    cy = 652.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000009.settings]
        background = false
        color = "on_surface"
        hide_when_no_media = false
        layout = "horizontal"
        shadow = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 162.0
    box_width = 367.0
    cx = 1826.2
    cy = 149.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = true
        background_padding = 20
        center_text = false
        clock_style = "digital"
        font_family = "FOT-Skip Std"
        format = "{:%I:%M %p}"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 110.0
    box_width = 335.0
    cx = 1826.2
    cy = 762.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        bands = 32
        centered = true
        mirrored = true
        show_when_idle = true

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 94.0
    box_width = 114.33
    cx = 1699.87
    cy = 886.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        font_family = "JetBrains Mono"
        background = true
        display = "gauge"
        gauge_layout = "vertical"
        shadow = true
        stat = "cpu_usage"
        stat2 = "cpu_temp"

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 94.0
    box_width = 114.33
    cx = 1952.53
    cy = 886.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        font_family = "JetBrains Mono"
        background = true
        display = "gauge"
        gauge_layout = "vertical"
        stat = "ram_pct"
        stat2 = ""

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    box_height = 94.0
    box_width = 114.33
    cx = 1826.2
    cy = 886.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        font_family = "JetBrains Mono"
        background_opacity = 0.80000000000000004
        display = "gauge"
        gauge_layout = "vertical"
        stat = "cpu_temp"
        stat2 = "cpu_temp"

    [desktop_widgets.widget.desktop-widget-0000000000000008]
    box_height = 333.0
    box_width = 367.0
    cx = 1826.2
    cy = 408.5
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "seal/centered_weather:desktop"

        [desktop_widgets.widget.desktop-widget-0000000000000008.settings]
        background = true
        background_padding = 16

[location]
auto_locate = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1024.0
    cy = 1006.4000854492188
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true

[plugins]
enabled = [ "noctalia/screen_recorder", "noctalia/timer", "noctalia/translator", "seal/centered_weather" ]

[shell]
lang = "en"

[theme]
builtin = "Noctalia"
community_palette = "Oxocarbon"
custom_palette = "motherboard"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "vibrant"

    [theme.templates]
    community_ids = [
        "claude-code",
        "spicetify",
        "brave",
        "discord",
        "libreoffice",
        "neovim",
        "vscode",
        "prismlauncher",
        "bat",
        "yazi",
        "fastfetch",
        "fzf",
        "lazygit",
        "micro",
        "papirus-icons"
    ]

[wallpaper.default]
path = "/home/seal/Pictures/WallPapers/we-3163965761.jpg"

[wallpaper.last]
path = "/home/seal/Pictures/WallPapers/we-3163965761.jpg"

[wallpaper.monitors.DP-1]
path = "/home/seal/Pictures/WallPapers/we-3163965761.jpg"

[weather]
unit = "imperial"