config_version = 14

[bar.default]
background_opacity = 0.87999998033046722
start = [ "launcher", "workspaces", "active_window" ]

[calendar]
enabled = true

    [calendar.account.personal_google]
    type = "google"

[control_center.calendar]
show_events_card = false

[desktop_widgets]
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000012",
    "desktop-widget-0000000000000009",
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000003",
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000005"
]

    [desktop_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000012]
    box_height = 360.0
    box_width = 540.0
    cx = 300.0
    cy = 225.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "seal/phantom_calendar:desktop"

        [desktop_widgets.widget.desktop-widget-0000000000000012.settings]
        background = false

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 110.0
    box_width = 335.0
    cx = 1826.2
    cy = 265.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = true
        background_color = "#000000"
        background_opacity = 0.95
        background_radius = 0.0
        bands = 32
        color_1 = "#ffffff"
        color_2 = "primary"
        centered = true
        mirrored = true
        show_when_idle = true

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 94.0
    box_width = 114.33
    cx = 1699.8699999999999
    cy = 1080.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background = true
        background_color = "#000000"
        background_radius = 0.0
        display = "gauge"
        font_family = "Anton"
        gauge_layout = "vertical"
        shadow = true
        stat = "cpu_usage"
        stat2 = "cpu_temp"

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 94.0
    box_width = 114.33
    cx = 1952.53
    cy = 1080.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        background = true
        background_color = "#000000"
        background_radius = 0.0
        display = "gauge"
        font_family = "Anton"
        gauge_layout = "vertical"
        stat = "ram_pct"
        stat2 = ""

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    box_height = 94.0
    box_width = 114.33
    cx = 1826.2
    cy = 1080.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        background_color = "#000000"
        background_radius = 0.0
        display = "gauge"
        font_family = "Anton"
        gauge_layout = "vertical"
        stat = "cpu_temp"
        stat2 = "cpu_temp"

    [desktop_widgets.widget.desktop-widget-0000000000000009]
    box_height = 110.0
    box_width = 335.0
    cx = 1826.2
    cy = 155.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000009.settings]
        background = true
        background_color = "#000000"
        background_opacity = 0.95
        background_radius = 0.0
        color = "#ffffff"
        font_family = "Anton"
        hide_when_no_media = false
        layout = "horizontal"
        shadow = true

[location]
auto_locate = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1024.0
    cy = 1006.4000854492188
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true

[plugins]
enabled = [
    "noctalia/screen_recorder",
    "noctalia/timer",
    "noctalia/translator",
    "seal/centered_weather",
    "seal/phantom_calendar"
]

[shell]
lang = "en"

[theme]
builtin = "Noctalia"
community_palette = "Oxocarbon"
custom_palette = "motherboard"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "vibrant"

    [theme.templates]
    community_ids = [
        "claude-code",
        "spicetify",
        "brave",
        "discord",
        "libreoffice",
        "vscode",
        "prismlauncher",
        "bat",
        "yazi",
        "fastfetch",
        "fzf",
        "lazygit",
        "micro",
        "papirus-icons"
    ]

[wallpaper.default]
path = "/home/seal/Pictures/WallPapers/we-3163965761.jpg"

[wallpaper.last]
path = "/home/seal/Pictures/WallPapers/we-3163965761.jpg"

[wallpaper.monitors.DP-1]
path = "/home/seal/Pictures/WallPapers/we-3163965761.jpg"

[weather]
unit = "imperial"