[colors.primary]
background = "#291415"
foreground = "#f3f2f2"

[colors.cursor]
text = "#291415"
cursor = "#f3f2f2"

[colors.selection]
text = "#b6afaf"
background = "#371b1c"

[colors.normal]
black = "#371b1c"
red = "#ed4240"
green = "#ec5f68"
yellow = "#e99049"
blue = "#e9e049"
magenta = "#f18d93"
cyan = "#f1ba8d"
white = "#f3f2f2"

[colors.bright]
black = "#716263"
red = "#ed4240"
green = "#ec5f68"
yellow = "#e99049"
blue = "#e9e049"
magenta = "#f18d93"
cyan = "#f1ba8d"
white = "#f3f2f2"
