fontforge.View.DefaultFont: 12pt system-ui,Deja Vu Sans
fontforge.View.LabelFont: ^View.DefaultFont Deja Vu Sans,unifont,unifont upper
fontforge.View.MonoFont: ^View.DefaultFont monospace,unifont
fontforge.View.SerifFont: ^View.DefaultFont serif
fontforge.View.Background: {{colors.surface.default.hex}}

fontforge.FontView.GlyphFGColor: {{colors.on_surface.default.hex}}
fontforge.FontView.GlyphInfoColor: {{colors.secondary.default.hex}}
fontforge.FontView.SlotOutlineColor: {{colors.on_surface.default.hex}}
fontforge.FontView.SlotDivisionColor: {{colors.outline_variant.default.hex}}
fontforge.FontView.LabelColor: {{colors.on_surface.default.hex}}
fontforge.FontView.UnencodedLabelColor: {{colors.on_surface_variant.default.hex}}
fontforge.FontView.MissingLabelColor: {{colors.error.default.hex}}
fontforge.FontView.EmptySlotFgColor: {{colors.outline_variant.default.hex}}
fontforge.FontView.SelectedColor: {{colors.primary.default.hex}}
fontforge.FontView.SelectedFgColor: {{colors.on_primary.default.hex}}
fontforge.FontView.ChangedColor: {{colors.tertiary.default.hex}}
fontforge.FontView.MissingBitmapColor: {{colors.error.default.hex}}
fontforge.FontView.MissingOutlineColor: #008000
fontforge.FontView.HintingNeededColor: {{colors.secondary.default.hex}}
fontforge.FontView.MetricsAdvanceAtColor: #008000
fontforge.FontView.MetricsAdvanceToColor: #008000
fontforge.FontView.MetricsBaselineColor: #0000c0
fontforge.FontView.MetricsGlyphContourColor: #a45a38
fontforge.FontView.MetricsOriginColor: #c00000
fontforge.FontView.Font: ^View.LabelFont

fontforge.CharView.PointColor: #ff0000
fontforge.CharView.FirstPointColor: #707000
fontforge.CharView.SelectedPointColor: #c8c800
fontforge.CharView.SelectedPointWidth: 2
fontforge.CharView.ExtremePointColor: #c00080
fontforge.CharView.PointOfInflectionColor: #008080
fontforge.CharView.AlmostHVColor: #00ff80
fontforge.CharView.NextCPColor: #007090
fontforge.CharView.PrevCPColor: #cc00cc
fontforge.CharView.SelectedCPColor: #ffffff
fontforge.CharView.AnchorColor: #0040ff
fontforge.CharView.LabelFont: 83% ^View.DefaultFont
fontforge.CharView.IconFont: 24pt ^View.SerifFont
fontforge.CharView.PointNumberFont: 66% ^View.DefaultFont

fontforge.CharView.ForegroundOutlineColor: {{colors.on_surface.default.hex}}
fontforge.CharView.ForegroundThickOutlineColor: #20707070
fontforge.CharView.FillColor: #80707070
fontforge.CharView.PreviewFillColor: #fe0f0f0f
fontforge.CharView.OpenPathColor: #40660000
fontforge.CharView.ClipPathColor: #0000ff
fontforge.CharView.BackgroundOutlineColor: #009800
fontforge.CharView.BackgroundThickOutlineColor: #20707070
fontforge.CharView.WidthColor: {{colors.on_surface.default.hex}}
fontforge.CharView.WidthSelColor: #00ff00
fontforge.CharView.LBearingSelColor: #00ff00
fontforge.CharView.LigatureCaretColor: #909040
fontforge.CharView.AnchoredOutlineColor: #0040ff
fontforge.CharView.CoordinateLineColor: {{colors.outline.default.hex}}
fontforge.CharView.AscentDescentColor: #ff808080
fontforge.CharView.ItalicCoordColor: {{colors.outline.default.hex}}
fontforge.CharView.MetricsLabelColor: {{colors.on_surface.default.hex}}
fontforge.CharView.TemplateOutlineColor: #009800
fontforge.CharView.RulerBigTickColor: #008000
fontforge.CharView.RulerCurrentTickColor: #ff0000
fontforge.CharView.RulerFont: 66% ^View.DefaultFont
fontforge.CharView.GuideOutlineColor: {{colors.outline.default.hex}}
fontforge.CharView.GuideDragColor: {{colors.on_surface.default.hex}}

fontforge.CharView.TraceColor: #008000
fontforge.CharView.OldOutlineColor: #008000
fontforge.CharView.TransformOriginColor: {{colors.on_surface.default.hex}}
fontforge.CharView.DraggingComparisonOutlineColor: #8800bb00
fontforge.CharView.DraggingComparisonAlphaChannelOverride: #88000000
fontforge.CharView.MeasureToolLineColor: {{colors.on_surface.default.hex}}
fontforge.CharView.MeasureToolPointColor: #ff0000
fontforge.CharView.MeasureToolPointSnappedColor: #00ff00
fontforge.CharView.MeasureToolCanvasNumbersColor: #ff0000
fontforge.CharView.MeasureToolCanvasNumbersSnappedColor: #00ff00
fontforge.CharView.MeasureToolWindowForeground: {{colors.on_surface.default.hex}}
fontforge.CharView.MeasureToolWindowBackground: {{colors.surface_container.default.hex}}
fontforge.CharView.MeasureToolFont: 76% ^View.MonoFont

fontforge.CharView.BlueValuesStippledColor: #808080ff
fontforge.CharView.FamilyBlueStippledColor: #80ff7070
fontforge.CharView.MDHintColor: #80e04040
fontforge.CharView.HintLabelColor: {{colors.on_surface.default.hex}}
fontforge.CharView.DHintColor: #80d0a0a0
fontforge.CharView.HHintColor: #80a0d0a0
fontforge.CharView.VHintColor: #80c0c0ff
fontforge.CharView.HFlexHintColor: #00ff00
fontforge.CharView.VFlexHintColor: #00ff00
fontforge.CharView.ConflictHintColor: #00ffff
fontforge.CharView.HHintActiveColor: #00a000
fontforge.CharView.VHintActiveColor: #0000ff
fontforge.CharView.DeltaGridColor: #cc0000

fontforge.CharView.GridFitOutlineColor: #009800
fontforge.CharView.GridFitWidthColor: {{colors.on_surface.default.hex}}
fontforge.CharView.RasterColor: #ffa0a0a0
fontforge.CharView.RasterNewColor: #ff909090
fontforge.CharView.RasterOldColor: #ffc0c0c0
fontforge.CharView.RasterGridColor: #ffb0b0ff
fontforge.CharView.RasterDarkColor: #ff606060
fontforge.CharView.BackgroundImageColor: #fe707070

fontforge.CharView.CVPaletteForegroundColor: {{colors.on_surface.default.hex}}
fontforge.CharView.CVPaletteBackgroundColor: {{colors.surface_container.default.hex}}
fontforge.CharView.Button3DEdgeLightColor: {{colors.outline_variant.default.hex}}
fontforge.CharView.Button3DEdgeDarkColor: {{colors.surface_container_lowest.default.hex}}
fontforge.CharView.Button3d: True
fontforge.CharView.LayersPalette.Font: 64% ^View.DefaultFont
fontforge.CharView.ToolsPalette.Font: 10px ^View.DefaultFont

fontforge.BitmapView.BitmapColor: {{colors.outline.default.hex}}
fontforge.BitmapView.OverviewColor: {{colors.on_surface.default.hex}}
fontforge.BitmapView.GuideColor: {{colors.outline.default.hex}}
fontforge.BitmapView.WidthGuideColor: {{colors.outline.default.hex}}
fontforge.BitmapView.GridColor: {{colors.outline.default.hex}}
fontforge.BitmapView.OutlineColor: #00ff00
fontforge.BitmapView.ActiveToolColor: #909000
fontforge.BitmapView.SelectedRegionColor: #909000
fontforge.BitmapView.ReferenceColor: {{colors.outline.default.hex}}
fontforge.BitmapView.SelectedReferenceColor: #909000
fontforge.BitmapView.ReferenceBorderColor: {{colors.outline.default.hex}}
fontforge.BitmapView.SelectedReferenceBorderColor: #606000

fontforge.MetricsView.Font: 76% ^View.DefaultFont
fontforge.MetricsView.GlyphColor: {{colors.on_surface.default.hex}}
fontforge.MetricsView.SelectedGlyphColor: {{colors.primary.default.hex}}
fontforge.MetricsView.DividerColor: {{colors.outline_variant.default.hex}}
fontforge.MetricsView.AdvanceWidthColor: {{colors.outline.default.hex}}
fontforge.MetricsView.ItalicAdvanceColor: {{colors.outline.default.hex}}
fontforge.MetricsView.KernLineColor: {{colors.tertiary.default.hex}}
fontforge.MetricsView.SideBearingLineColor: {{colors.outline.default.hex}}

fontforge.BDFProperties.Font: 83% ^View.DefaultFont
fontforge.Combinations.Font: 76% ^View.DefaultFont
fontforge.CVT.Font: 76% ^View.MonoFont
fontforge.DebugView.Background: {{colors.surface.default.hex}}
fontforge.DebugView.Font: 76% ^View.DefaultFont
fontforge.FontInfo.OriginLineColor: {{colors.outline.default.hex}}
fontforge.FontInfo.Font: ^View.DefaultFont
fontforge.GlyphInfo.Font: ^View.MonoFont
fontforge.Groups.Font: ^View.DefaultFont
fontforge.Histogram.GraphColor: {{colors.primary.default.hex}}
fontforge.Histogram.Font: 83% ^View.DefaultFont
fontforge.KernClass.Font: ^View.MonoFont
fontforge.KernClass.TextColor: {{colors.on_surface.default.hex}}
fontforge.KernFormat.Font: ^View.DefaultFont
fontforge.KernFormat.BoldFont: bold ^View.DefaultFont
fontforge.Math.Font: ^View.DefaultFont
fontforge.Math.BoldFont: bold ^Math.Font

fontforge.Prefs.MonoFont: ^View.MonoFont
fontforge.SearchView.Font: ^View.DefaultFont
fontforge.SearchView.BoldFont: bold ^SearchView.Font
fontforge.ShowAtt.SelectColor: #ff0000
fontforge.ShowAtt.GlyphNameColor: {{colors.primary.default.hex}}
fontforge.ShowATT.Font: ^View.DefaultFont
fontforge.ShowATT.MonoFont: ^View.MonoFont
fontforge.StateMachine.Font: ^View.MonoFont
fontforge.TTInstruction.Font: 76% ^View.MonoFont
fontforge.Validate.Font: 92% ^View.DefaultFont
fontforge.Warnings.Font: 81% ^View.DefaultFont

fontforge.Splash.Foreground: {{colors.on_surface.default.hex}}
fontforge.Splash.Background: {{colors.surface.default.hex}}
fontforge.Splash.Font: 10pt ^View.DefaultFont
fontforge.Splash.ItalicFont: italic ^Splash.Font
fontforge.Splash.MonoFont: 10pt ^View.MonoFont
fontforge.Splash.Image: splash2019.png

fontforge.SFTextArea.Box.ActiveInner: True
fontforge.SFTextArea.Box.Padding: 1
fontforge.SFTextArea.Font: 83% ^View.MonoFont

Gdraw.Background: {{colors.surface.default.hex}}
Gdraw.Foreground: {{colors.on_surface.default.hex}}
Gdraw.WarningForeground: {{colors.error.default.hex}}
Gdraw.ScreenResolution: 0
Gdraw.MultiClickTime: 200
Gdraw.MultiClickWiggle: 3
Gdraw.SelectionNotifyTimeout: 2
Gdraw.TwoButtonFixup: True
Gdraw.MacOSXCmd: False
Gdraw.Synchronize: False

Gdraw.GGadget.Popup.Font: 67% ^View.DefaultFont
Gdraw.GGadget.Popup.Foreground: {{colors.on_surface.default.hex}}
Gdraw.GGadget.Popup.Background: {{colors.surface_container_highest.default.hex}}
Gdraw.GGadget.Popup.Delay: 1000
Gdraw.GGadget.Popup.LifeTime: 20000

Gdraw.GProgress.Font: ^View.MonoFont
Gdraw.GProgress.Background: {{colors.surface_container.default.hex}}
Gdraw.GProgress.Foreground: {{colors.on_surface.default.hex}}
Gdraw.GProgress.FillColor: {{colors.primary.default.hex}}

Gdraw.GGadget.Box.BorderInner: False
Gdraw.GGadget.Box.BorderOuter: False
Gdraw.GGadget.Box.ActiveInner: False
Gdraw.GGadget.Box.ShadowOuter: False
Gdraw.GGadget.Box.DoDepressedBackground: False
Gdraw.GGadget.Box.DrawDefault: False
Gdraw.GGadget.Box.GradientBG: False
Gdraw.GGadget.Box.NormalForeground: {{colors.on_surface.default.hex}}
Gdraw.GGadget.Box.DisabledForeground: {{colors.outline.default.hex}}
Gdraw.GGadget.Box.NormalBackground: {{colors.surface_container.default.hex}}
Gdraw.GGadget.Box.DisabledBackground: {{colors.surface_container.default.hex}}
Gdraw.GGadget.Box.PressedBackground: {{colors.surface_container.default.hex}}
Gdraw.GGadget.Box.GradientStartCol: {{colors.surface_container_highest.default.hex}}
Gdraw.GGadget.Box.BorderBrightest: {{colors.outline.default.hex}}
Gdraw.GGadget.Box.BorderBrighter: {{colors.outline.default.hex}}
Gdraw.GGadget.Box.BorderDarker: {{colors.outline.default.hex}}
Gdraw.GGadget.Box.BorderDarkest: {{colors.outline.default.hex}}
Gdraw.GGadget.Box.BorderInnerCol: {{colors.on_surface.default.hex}}
Gdraw.GGadget.Box.BorderOuterCol: {{colors.on_surface.default.hex}}
Gdraw.GGadget.Box.ActiveBorder: {{colors.primary.default.hex}}
Gdraw.GGadget.Box.BorderType: none
Gdraw.GGadget.Box.BorderShape: rect
Gdraw.GGadget.Box.BorderWidth: 1
Gdraw.GGadget.Box.Padding: 2
Gdraw.GGadget.Box.Radius: 0
Gdraw.GGadget.Font: 83% ^View.DefaultFont

Gdraw.GGadget.Skip: 6
Gdraw.GGadget.LineSkip: 3
Gdraw.GGadget.FirstLine: 6
Gdraw.GGadget.LeftMargin: 6
Gdraw.GGadget.TextImageSkip: 4
Gdraw.GGadget.ImagePath: ~/.FontForge/tango-ct.theme:~/.FontForge/tango-ct.theme/tango:/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps/:=

Gdraw.GListMark.Box.BorderInner: True
Gdraw.GListMark.Box.NormalBackground: {{colors.surface_container.default.hex}}
Gdraw.GListMark.Box.BorderBrightest: {{colors.outline_variant.default.hex}}
Gdraw.GListMark.Box.BorderBrighter: {{colors.outline_variant.default.hex}}
Gdraw.GListMark.Box.BorderDarker: {{colors.outline_variant.default.hex}}
Gdraw.GListMark.Box.BorderDarkest: {{colors.outline_variant.default.hex}}
Gdraw.GListMark.Box.BorderInnerCol: {{colors.outline.default.hex}}
Gdraw.GListMark.Box.BorderType: lowered
Gdraw.GListMark.Box.BorderWidth: 2
Gdraw.GListMark.Box.Padding: 0
Gdraw.GListMark.Image: downarrow.png
Gdraw.GListMark.DisabledImage: downarrow_disabled.png
Gdraw.GListMark.Width: 8

Gdraw.GLabel.Box.BorderType: none
Gdraw.GLabel.Box.BorderWidth: 0
Gdraw.GLabel.Box.Padding: 0
Gdraw.GLabel.Font: 83% ^View.DefaultFont

Gdraw.GButton.Box.BorderInner: True
Gdraw.GButton.Box.BorderOuter: True
Gdraw.GButton.Box.DoDepressedBackground: True
Gdraw.GButton.Box.DrawDefault: False
Gdraw.GButton.Box.GradientBG: True
Gdraw.GButton.Box.NormalBackground: {{colors.surface_container_high.default.hex}}
Gdraw.GButton.Box.GradientStartCol: {{colors.surface_container_highest.default.hex}}
Gdraw.GButton.Box.BorderInnerCol: {{colors.outline_variant.default.hex}}
Gdraw.GButton.Box.BorderOuterCol: {{colors.outline_variant.default.hex}}
Gdraw.GButton.Box.BorderType: box
Gdraw.GButton.Box.BorderShape: roundrect
Gdraw.GButton.Box.Padding: 1
Gdraw.GButton.Box.Radius: 3
Gdraw.GButton.Font: 83% ^View.DefaultFont
Gdraw.GButton.ShiftOnPress: False

Gdraw.GDefaultButton.Box.BorderBrightest: {{colors.primary.default.hex}}
Gdraw.GDefaultButton.Box.BorderBrighter: {{colors.primary.default.hex}}
Gdraw.GDefaultButton.Box.BorderDarker: {{colors.primary.default.hex}}
Gdraw.GDefaultButton.Box.BorderDarkest: {{colors.primary.default.hex}}
Gdraw.GDefaultButton.Box.BorderOuterCol: {{colors.primary_container.default.hex}}

Gdraw.GDropList.Box.BorderType: none
Gdraw.GDropList.Box.BorderShape: rect

Gdraw.GRadio.Box.BorderType: none
Gdraw.GRadio.Box.Padding: 0

Gdraw.GRadioOn.Box.DoDepressedBackground: False
Gdraw.GRadioOn.Box.PressedBackground: {{colors.primary.default.hex}}
Gdraw.GRadioOn.Box.BorderBrighter: {{colors.outline_variant.default.hex}}
Gdraw.GRadioOn.Box.BorderDarkest: {{colors.outline_variant.default.hex}}
Gdraw.GRadioOn.Box.BorderType: none
Gdraw.GRadioOn.Box.BorderShape: rect
Gdraw.GRadioOn.Box.Padding: 3
Gdraw.GRadioOn.Image: radio_on.png
Gdraw.GRadioOn.DisabledImage: radio_on_disabled.png

Gdraw.GRadioOff.Box.DoDepressedBackground: False
Gdraw.GRadioOff.Box.BorderBrighter: {{colors.outline_variant.default.hex}}
Gdraw.GRadioOff.Box.BorderDarkest: {{colors.outline_variant.default.hex}}
Gdraw.GRadioOff.Box.BorderType: none
Gdraw.GRadioOff.Box.BorderShape: rect
Gdraw.GRadioOff.Box.BorderWidth: 0
Gdraw.GRadioOff.Box.Padding: 0
Gdraw.GRadioOff.Image: radio_off.png
Gdraw.GRadioOff.DisabledImage: radio_off_disabled.png

Gdraw.GCheckBox.Box.BorderType: none
Gdraw.GCheckBox.Box.Padding: 0
Gdraw.GCheckBox.Font: 83% ^View.DefaultFont

Gdraw.GCheckBoxOn.Box.DoDepressedBackground: False
Gdraw.GCheckBoxOn.Box.PressedBackground: {{colors.primary.default.hex}}
Gdraw.GCheckBoxOn.Box.BorderBrighter: {{colors.outline_variant.default.hex}}
Gdraw.GCheckBoxOn.Box.BorderDarkest: {{colors.outline_variant.default.hex}}
Gdraw.GCheckBoxOn.Box.BorderType: none
Gdraw.GCheckBoxOn.Box.BorderShape: rect
Gdraw.GCheckBoxOn.Box.Padding: 3
Gdraw.GCheckBoxOn.Image: check_on.png
Gdraw.GCheckBoxOn.DisabledImage: check_on_disabled.png

Gdraw.GCheckBoxOff.Box.DoDepressedBackground: False
Gdraw.GCheckBoxOff.Box.BorderBrighter: {{colors.outline_variant.default.hex}}
Gdraw.GCheckBoxOff.Box.BorderDarkest: {{colors.outline_variant.default.hex}}
Gdraw.GCheckBoxOff.Box.BorderType: none
Gdraw.GCheckBoxOff.Box.BorderShape: rect
Gdraw.GCheckBoxOff.Box.Padding: 3
Gdraw.GCheckBoxOff.Image: check_off.png
Gdraw.GCheckBoxOff.DisabledImage: check_off_disabled.png

Gdraw.GVisibilityBox.Box.BorderType: none
Gdraw.GVisibilityBox.Box.Padding: 0

Gdraw.GVisibilityBoxOn.Box.BorderType: none
Gdraw.GVisibilityBoxOn.Box.Padding: 1
Gdraw.GVisibilityBoxOn.Image: check_on.png
Gdraw.GVisibilityBoxOn.DisabledImage: check_on_disabled.png

Gdraw.GVisibilityBoxOff.Box.BorderType: none
Gdraw.GVisibilityBoxOff.Box.Padding: 1
Gdraw.GVisibilityBoxOff.Image: check_off.png
Gdraw.GVisibilityBoxOff.DisabledImage: check_off_disabled.png

Gdraw.GTextField.Box.BorderInner: True
Gdraw.GTextField.Box.NormalBackground: {{colors.surface_container_low.default.hex}}
Gdraw.GTextField.Box.BorderBrightest: {{colors.outline_variant.default.hex}}
Gdraw.GTextField.Box.BorderBrighter: {{colors.outline_variant.default.hex}}
Gdraw.GTextField.Box.BorderDarker: {{colors.outline_variant.default.hex}}
Gdraw.GTextField.Box.BorderDarkest: {{colors.outline_variant.default.hex}}
Gdraw.GTextField.Box.BorderInnerCol: {{colors.outline.default.hex}}
Gdraw.GTextField.Box.BorderType: lowered
Gdraw.GTextField.Box.BorderShape: roundrect
Gdraw.GTextField.Box.Padding: 2
Gdraw.GTextField.Box.Radius: 3
Gdraw.GTextField.Font: 83% ^View.MonoFont

Gdraw.GComboBox.Box.BorderBrightest: {{colors.outline_variant.default.hex}}
Gdraw.GComboBox.Box.BorderBrighter: {{colors.outline_variant.default.hex}}
Gdraw.GComboBox.Box.BorderType: box

Gdraw.GComboBoxMenu.Box.BorderOuter: True
Gdraw.GComboBoxMenu.Box.GradientBG: True
Gdraw.GComboBoxMenu.Box.GradientStartCol: {{colors.surface_container_highest.default.hex}}
Gdraw.GComboBoxMenu.Box.BorderBrightest: {{colors.outline.default.hex}}
Gdraw.GComboBoxMenu.Box.BorderBrighter: {{colors.outline.default.hex}}
Gdraw.GComboBoxMenu.Box.BorderDarker: {{colors.outline.default.hex}}
Gdraw.GComboBoxMenu.Box.BorderDarkest: {{colors.outline.default.hex}}
Gdraw.GComboBoxMenu.Box.BorderInnerCol: {{colors.outline_variant.default.hex}}
Gdraw.GComboBoxMenu.Box.BorderOuterCol: {{colors.outline_variant.default.hex}}
Gdraw.GComboBoxMenu.Box.Padding: 2


Gdraw.GNumericFieldSpinner.Box.BorderOuter: True
Gdraw.GNumericFieldSpinner.Box.GradientBG: True
Gdraw.GNumericFieldSpinner.Box.GradientStartCol: {{colors.surface_container_highest.default.hex}}
Gdraw.GNumericFieldSpinner.Box.BorderBrightest: {{colors.outline.default.hex}}
Gdraw.GNumericFieldSpinner.Box.BorderBrighter: {{colors.outline.default.hex}}
Gdraw.GNumericFieldSpinner.Box.BorderDarker: {{colors.outline.default.hex}}
Gdraw.GNumericFieldSpinner.Box.BorderDarkest: {{colors.outline.default.hex}}
Gdraw.GNumericFieldSpinner.Box.BorderInnerCol: {{colors.outline_variant.default.hex}}
Gdraw.GNumericFieldSpinner.Box.BorderOuterCol: {{colors.outline_variant.default.hex}}
Gdraw.GNumericFieldSpinner.Box.BorderType: box
Gdraw.GNumericFieldSpinner.Box.BorderWidth: 1
Gdraw.GNumericFieldSpinner.Box.Padding: 2

Gdraw.GList.Box.BorderOuter: False
Gdraw.GList.Box.NormalBackground: {{colors.surface_container_low.default.hex}}
Gdraw.GList.Box.BorderType: box
Gdraw.GList.Font: 83% ^View.DefaultFont

Gdraw.GScrollBar.Box.BorderOuter: False
Gdraw.GScrollBar.Box.NormalForeground: {{colors.surface_container.default.hex}}
Gdraw.GScrollBar.Box.DisabledForeground: {{colors.surface_container.default.hex}}
Gdraw.GScrollBar.Box.NormalBackground: {{colors.surface_container.default.hex}}
Gdraw.GScrollBar.Box.GradientStartCol: {{colors.surface_container.default.hex}}
Gdraw.GScrollBar.Box.BorderBrightest: {{colors.surface_container.default.hex}}
Gdraw.GScrollBar.Box.BorderDarker: {{colors.surface_container.default.hex}}
Gdraw.GScrollBar.Box.BorderDarkest: {{colors.surface_container.default.hex}}
Gdraw.GScrollBar.Box.BorderInnerCol: {{colors.surface_container.default.hex}}
Gdraw.GScrollBar.Box.BorderOuterCol: {{colors.surface_container.default.hex}}
Gdraw.GScrollBar.Box.ActiveBorder: {{colors.surface_container.default.hex}}
Gdraw.GScrollBar.Box.BorderType: none
Gdraw.GScrollBar.Box.BorderWidth: 0
Gdraw.GScrollBar.Box.Padding: 2
Gdraw.GScrollBar.StartTime: 300
Gdraw.GScrollBar.RepeatTime: 200
Gdraw.GScrollBar.Width: 11

Gdraw.GScrollBarThumb.Box.NormalForeground: {{colors.outline.default.hex}}
Gdraw.GScrollBarThumb.Box.DisabledForeground: {{colors.outline.default.hex}}
Gdraw.GScrollBarThumb.Box.NormalBackground: {{colors.outline_variant.default.hex}}
Gdraw.GScrollBarThumb.Box.DisabledBackground: {{colors.outline_variant.default.hex}}
Gdraw.GScrollBarThumb.Box.PressedBackground: {{colors.outline_variant.default.hex}}
Gdraw.GScrollBarThumb.Box.GradientStartCol: {{colors.outline_variant.default.hex}}
Gdraw.GScrollBarThumb.Box.BorderBrightest: {{colors.outline_variant.default.hex}}
Gdraw.GScrollBarThumb.Box.BorderBrighter: {{colors.outline_variant.default.hex}}
Gdraw.GScrollBarThumb.Box.BorderDarker: {{colors.outline_variant.default.hex}}
Gdraw.GScrollBarThumb.Box.BorderDarkest: {{colors.outline_variant.default.hex}}
Gdraw.GScrollBarThumb.Box.BorderInnerCol: {{colors.outline_variant.default.hex}}
Gdraw.GScrollBarThumb.Box.BorderOuterCol: {{colors.outline_variant.default.hex}}
Gdraw.GScrollBarThumb.Box.ActiveBorder: {{colors.outline_variant.default.hex}}
Gdraw.GScrollBarThumb.Box.BorderType: box
Gdraw.GScrollBarThumb.Box.BorderShape: roundrect
Gdraw.GScrollBarThumb.Box.BorderWidth: 0
Gdraw.GScrollBarThumb.Box.Padding: 50
Gdraw.GScrollBarThumb.Box.Radius: 10

Gdraw.GGroup.Box.NormalBackground: {{colors.surface_container_low.default.hex}}
Gdraw.GGroup.Box.DisabledBackground: {{colors.surface_container_low.default.hex}}
Gdraw.GGroup.Box.BorderType: none
Gdraw.GGroup.Box.BorderShape: rect
Gdraw.GGroup.Box.Padding: 0

Gdraw.GLine.Box.BorderBrightest: {{colors.outline_variant.default.hex}}
Gdraw.GLine.Box.BorderBrighter: {{colors.outline_variant.default.hex}}
Gdraw.GLine.Box.BorderType: engraved
Gdraw.GLine.Box.BorderShape: rect
Gdraw.GLine.Box.BorderWidth: 2
Gdraw.GLine.Box.Padding: 0

Gdraw.GHVBox.Box.BorderType: none
Gdraw.GHVBox.Box.BorderShape: rect
Gdraw.GHVBox.Box.Padding: 0

Gdraw.GGroup.Box.NormalBackground: {{colors.surface_container_low.default.hex}}
Gdraw.GGroup.Box.DisabledBackground: {{colors.surface_container_low.default.hex}}
Gdraw.GGroup.Box.BorderType: none
Gdraw.GGroup.Box.BorderShape: rect
Gdraw.GGroup.Box.Padding: 0

Gdraw.GMenuBar.Box.BorderOuter: False
Gdraw.GMenuBar.Box.GradientStartCol: {{colors.surface_container_highest.default.hex}}
Gdraw.GMenuBar.Box.BorderInnerCol: {{colors.surface_container.default.hex}}
Gdraw.GMenuBar.Box.ActiveBorder: {{colors.primary.default.hex}}
Gdraw.GMenuBar.Box.BorderShape: rect
Gdraw.GMenuBar.Box.BorderWidth: 1
Gdraw.GMenuBar.Box.Radius: 2
Gdraw.GMenuBar.Font: 83% ^View.DefaultFont

Gdraw.GMenu.Box.BorderOuter: True
Gdraw.GMenu.Box.NormalBackground: {{colors.surface_container_low.default.hex}}
Gdraw.GMenu.Box.BorderOuterCol: {{colors.outline_variant.default.hex}}
Gdraw.GMenu.Box.BorderShape: rect
Gdraw.GMenu.Box.Padding: 3
Gdraw.GMenu.Font: 83% ^View.DefaultFont
Gdraw.GMenu.MacIcons: False
Gdraw.GMenu.3DLook: True
Gdraw.GMenu.Grab: True

Gdraw.GMatrixEdit.Box.NormalBackground: {{colors.surface_container_low.default.hex}}
Gdraw.GMatrixEdit.Box.DisabledBackground: {{colors.surface_container_low.default.hex}}
Gdraw.GMatrixEdit.Box.BorderType: none
Gdraw.GMatrixEdit.Box.BorderShape: rect
Gdraw.GMatrixEdit.Box.BorderWidth: 0
Gdraw.GMatrixEdit.Box.Padding: 0
Gdraw.GMatrixEdit.Font: ^View.MonoFont

Gdraw.GMatrixEdit.TitleBG: {{colors.surface_container_highest.default.hex}}
Gdraw.GMatrixEdit.TitleFG: {{colors.on_surface.default.hex}}
Gdraw.GMatrixEdit.TitleDivider: {{colors.outline_variant.default.hex}}
Gdraw.GMatrixEdit.RuleCol: {{colors.outline_variant.default.hex}}
Gdraw.GMatrixEdit.FrozenCol: {{colors.error.default.hex}}
Gdraw.GMatrixEdit.ActiveCol: {{colors.primary.default.hex}}
Gdraw.GMatrixEdit.ActiveBG: {{colors.primary_container.default.hex}}
Gdraw.GMatrixEdit.TitleFont: bold 67% ^View.MonoFont

Gdraw.GMatrixEditButton.Box.BorderInner: True
Gdraw.GMatrixEditButton.Box.NormalBackground: {{colors.surface_container_high.default.hex}}
Gdraw.GMatrixEditButton.Box.DisabledBackground: {{colors.surface_container.default.hex}}
Gdraw.GMatrixEditButton.Box.BorderWidth: 0
Gdraw.GMatrixEditButton.Box.Padding: 0

Gdraw.GDrawable.Box.BorderType: none
Gdraw.GDrawable.Box.BorderWidth: 0
Gdraw.GDrawable.Box.Padding: 0

Gdraw.GTabSet.Box.BorderType: box
Gdraw.GTabSet.Box.BorderShape: roundrect
Gdraw.GTabSet.Box.BorderWidth: 1
Gdraw.GTabSet.Box.Radius: 2
Gdraw.GTabSet.Font: 83% ^View.DefaultFont
Gdraw.GTabSet.CloseColor: {{colors.error.default.hex}}


