stream.rules = [
  {
    matches = [
      { application.name = "Spotify" }
    ]
    actions = {
      update-props = {
        state.restore-props = false
        state.default-volume = 0.5
      }
    }
  }
]
